plugins {
    id 'com.android.application'
}

android {
    namespace 'com.naturemoments.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.naturemoments.app"
        minSdk 24
        targetSdk 34
        versionCode 23
        versionName "2.5.7"
    }

    signingConfigs {
        release {
            storeFile file('release-key.jks')
            storePassword 'naturemoments'
            keyAlias 'naturemoments'
            keyPassword 'naturemoments'
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    aaptOptions {
        noCompress 'mp4', 'm4a', 'webm'
    }
}

dependencies {
    constraints {
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22") {
            because("kotlin-stdlib-jdk7 is now part of kotlin-stdlib")
        }
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22") {
            because("kotlin-stdlib-jdk8 is now part of kotlin-stdlib")
        }
    }

    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.webkit:webkit:1.10.0'
    implementation 'com.google.android.gms:play-services-ads:23.0.0'
}
